export const exampleDataEn = {
  "2023": {
    messages: {
      monthlyData: [
        {
          month: "months.january",
          MJ: 167,
          "Spider Man": 117,
        },
        {
          month: "months.february",
          MJ: 116,
          "Spider Man": 126,
        },
        {
          month: "months.march",
          MJ: 94,
          "Spider Man": 63,
        },
        {
          month: "months.april",
          MJ: 84,
          "Spider Man": 85,
        },
        {
          month: "months.may",
          MJ: 315,
          "Spider Man": 252,
        },
        {
          month: "months.june",
          MJ: 88,
          "Spider Man": 101,
        },
        {
          month: "months.july",
          MJ: 961,
          "Spider Man": 760,
        },
        {
          month: "months.august",
          MJ: 133,
          "Spider Man": 93,
        },
        {
          month: "months.september",
          MJ: 74,
          "Spider Man": 71,
        },
        {
          month: "months.october",
          MJ: 401,
          "Spider Man": 210,
        },
        {
          month: "months.november",
          MJ: 708,
          "Spider Man": 676,
        },
        {
          month: "months.december",
          MJ: 455,
          "Spider Man": 426,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    timeOfDay: {
      hourCounts: [
        {
          hour: 0,
          label: "00:00",
          MJ: 205,
          "Spider Man": 153,
        },
        {
          hour: 1,
          label: "01:00",
          MJ: 127,
          "Spider Man": 182,
        },
        {
          hour: 2,
          label: "02:00",
          MJ: 5,
          "Spider Man": 12,
        },
        {
          hour: 3,
          label: "03:00",
          MJ: 30,
          "Spider Man": 14,
        },
        {
          hour: 4,
          label: "04:00",
          MJ: 1,
          "Spider Man": 0,
        },
        {
          hour: 5,
          label: "05:00",
          MJ: 2,
          "Spider Man": 1,
        },
        {
          hour: 6,
          label: "06:00",
          MJ: 9,
          "Spider Man": 3,
        },
        {
          hour: 7,
          label: "07:00",
          MJ: 19,
          "Spider Man": 20,
        },
        {
          hour: 8,
          label: "08:00",
          MJ: 20,
          "Spider Man": 6,
        },
        {
          hour: 9,
          label: "09:00",
          MJ: 93,
          "Spider Man": 68,
        },
        {
          hour: 10,
          label: "10:00",
          MJ: 157,
          "Spider Man": 148,
        },
        {
          hour: 11,
          label: "11:00",
          MJ: 172,
          "Spider Man": 141,
        },
        {
          hour: 12,
          label: "12:00",
          MJ: 221,
          "Spider Man": 192,
        },
        {
          hour: 13,
          label: "13:00",
          MJ: 143,
          "Spider Man": 147,
        },
        {
          hour: 14,
          label: "14:00",
          MJ: 146,
          "Spider Man": 164,
        },
        {
          hour: 15,
          label: "15:00",
          MJ: 227,
          "Spider Man": 270,
        },
        {
          hour: 16,
          label: "16:00",
          MJ: 320,
          "Spider Man": 196,
        },
        {
          hour: 17,
          label: "17:00",
          MJ: 368,
          "Spider Man": 275,
        },
        {
          hour: 18,
          label: "18:00",
          MJ: 226,
          "Spider Man": 178,
        },
        {
          hour: 19,
          label: "19:00",
          MJ: 225,
          "Spider Man": 143,
        },
        {
          hour: 20,
          label: "20:00",
          MJ: 261,
          "Spider Man": 170,
        },
        {
          hour: 21,
          label: "21:00",
          MJ: 140,
          "Spider Man": 120,
        },
        {
          hour: 22,
          label: "22:00",
          MJ: 303,
          "Spider Man": 212,
        },
        {
          hour: 23,
          label: "23:00",
          MJ: 176,
          "Spider Man": 165,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    firstMessages: {
      monthlyInitiations: [
        {
          month: "months.january",
          MJ: 16,
          "Spider Man": 7,
        },
        {
          month: "months.february",
          MJ: 9,
          "Spider Man": 13,
        },
        {
          month: "months.march",
          MJ: 8,
          "Spider Man": 12,
        },
        {
          month: "months.april",
          MJ: 11,
          "Spider Man": 17,
        },
        {
          month: "months.may",
          MJ: 10,
          "Spider Man": 9,
        },
        {
          month: "months.june",
          MJ: 9,
          "Spider Man": 14,
        },
        {
          month: "months.july",
          MJ: 9,
          "Spider Man": 6,
        },
        {
          month: "months.august",
          MJ: 12,
          "Spider Man": 10,
        },
        {
          month: "months.september",
          MJ: 10,
          "Spider Man": 11,
        },
        {
          month: "months.october",
          MJ: 14,
          "Spider Man": 14,
        },
        {
          month: "months.november",
          MJ: 11,
          "Spider Man": 11,
        },
        {
          month: "months.december",
          MJ: 10,
          "Spider Man": 12,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    reactions: {
      topReactions: [
        {
          emoji: "😁",
          stats: {
            totalCount: 44,
            userCounts: {
              "Spider Man": 37,
              MJ: 7,
            },
          },
        },
        {
          emoji: "🔥",
          stats: {
            totalCount: 26,
            userCounts: {
              "Spider Man": 17,
              MJ: 9,
            },
          },
        },
        {
          emoji: "❤",
          stats: {
            totalCount: 25,
            userCounts: {
              "Spider Man": 23,
              MJ: 2,
            },
          },
        },
        {
          emoji: "🥰",
          stats: {
            totalCount: 24,
            userCounts: {
              "Spider Man": 5,
              MJ: 19,
            },
          },
        },
        {
          emoji: "👍",
          stats: {
            totalCount: 23,
            userCounts: {
              "Spider Man": 8,
              MJ: 15,
            },
          },
        },
      ],
      userFavorites: [
        {
          user: "Spider Man",
          emoji: "😁",
          count: 37,
        },
        {
          user: "MJ",
          emoji: "🥰",
          count: 19,
        },
      ],
    },
    voiceMessages: {
      userStats: [
        {
          user: "Spider Man",
          count: 61,
          longestMessage: 82,
          userId: "paukid",
        },
        {
          user: "MJ",
          count: 58,
          longestMessage: 235,
          userId: "mjid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 58,
        longestMessage: 235,
        userId: "mjid",
      },
      totalCount: 119,
    },
    videoMessages: {
      userStats: [
        {
          user: "MJ",
          count: 147,
          longestMessage: 60,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 34,
          longestMessage: 57,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 147,
        longestMessage: 60,
        userId: "mjid",
      },
      totalCount: 181,
    },
    wordCloud: {
      wordData: [
        { text: "me", value: 185 },
        { text: "need", value: 146 },
        { text: "you", value: 107 },
        { text: "good", value: 107 },
        { text: "you", value: 106 },
        { text: "can", value: 105 },
        { text: "only", value: 87 },
        { text: "also", value: 85 },
        { text: "want", value: 83 },
        { text: "just", value: 82 },
        { text: "if", value: 82 },
        { text: "later", value: 70 },
        { text: "have", value: 69 },
        { text: "bye", value: 68 },
        { text: "minutes", value: 67 },
        { text: "after", value: 66 },
        { text: "will", value: 62 },
        { text: "hi", value: 60 },
        { text: "will", value: 58 },
        { text: "to", value: 55 },
        { text: "today", value: 55 },
        { text: "was", value: 55 },
        { text: "when", value: 54 },
        { text: "let's", value: 50 },
        { text: "fine", value: 49 },
        { text: "actually", value: 45 },
        { text: "could", value: 44 },
        { text: "haha", value: 44 },
        { text: "then", value: 43 },
        { text: "because", value: 42 },
        { text: "home", value: 41 },
        { text: "maybe", value: 41 },
        { text: "thought", value: 41 },
        { text: "back", value: 41 },
        { text: "more", value: 41 },
        { text: "sleep", value: 39 },
        { text: "morning", value: 39 },
        { text: "why", value: 38 },
        { text: "like", value: 38 },
        { text: "tomorrow", value: 37 },
        { text: "know", value: 37 },
        { text: "day", value: 36 },
        { text: "now", value: 36 },
        { text: "such", value: 36 },
        { text: "alright", value: 35 },
        { text: "even", value: 35 },
        { text: "very", value: 34 },
        { text: "nowadays", value: 34 },
        { text: "one", value: 33 },
        { text: "nothing", value: 32 },
        { text: "goodnight", value: 31 },
        { text: "may", value: 30 },
        { text: "damn", value: 30 },
        { text: "go", value: 30 },
        { text: "will", value: 29 },
        { text: "how much", value: 29 },
        { text: "think", value: 29 },
        { text: "a lot", value: 29 },
        { text: "by the way", value: 28 },
        { text: "sorta", value: 28 },
        { text: "night", value: 27 },
        { text: "wanted", value: 26 },
        { text: "want", value: 26 },
        { text: "seems", value: 26 },
        { text: "soon", value: 25 },
        { text: "lol", value: 25 },
        { text: "rofl", value: 24 },
        { text: "probably", value: 24 },
        { text: "hehe", value: 24 },
        { text: "was", value: 23 },
        { text: "other", value: 23 },
        { text: "time", value: 22 },
        { text: "watch", value: 22 },
        { text: "what for", value: 22 },
        { text: "buy", value: 22 },
        { text: "works", value: 22 },
        { text: "yesterday", value: 22 },
        { text: "what", value: 21 },
        { text: "so", value: 20 },
        { text: "shall", value: 20 },
        { text: "work", value: 20 },
        { text: "myself", value: 19 },
        { text: "store", value: 19 },
        { text: "long", value: 19 },
        { text: "any", value: 19 },
        { text: "this", value: 19 },
        { text: "with you", value: 19 },
        { text: "cool", value: 19 },
        { text: "things", value: 19 },
        { text: "like that", value: 19 },
        { text: "decided", value: 19 },
        { text: "awesome", value: 19 },
        { text: "afterwards", value: 19 },
        { text: "again", value: 19 },
        { text: "thanks", value: 18 },
        { text: "where", value: 18 },
        { text: "decent", value: 18 },
        { text: "hope", value: 18 },
        { text: "sitting", value: 18 },
        { text: "which", value: 17 },
      ],
    },
    forwardedMessages: {
      userStats: [
        {
          user: "Spider Man",
          userId: "paukid",
          sources: [
            {
              source: "The Daily Bugle",
              count: 54,
            },
            {
              source: "Stan Lee",
              count: 23,
            },
            {
              source: "Hulk",
              count: 19,
            },
          ],
        },
        {
          user: "MJ",
          userId: "mjid",
          sources: [
            {
              source: "Stan Lee",
              count: 14,
            },
            {
              source: "Typical New York",
              count: 5,
            },
            {
              source: "The New York Times",
              count: 3,
            },
          ],
        },
      ],
      totalCount: 206,
    },
    settings: {
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
      years: [2025, 2024, 2023],
    },
  },
  "2024": {
    messages: {
      monthlyData: [
        {
          month: "months.january",
          MJ: 681,
          "Spider Man": 487,
        },
        {
          month: "months.february",
          MJ: 363,
          "Spider Man": 295,
        },
        {
          month: "months.march",
          MJ: 134,
          "Spider Man": 151,
        },
        {
          month: "months.april",
          MJ: 134,
          "Spider Man": 149,
        },
        {
          month: "months.may",
          MJ: 234,
          "Spider Man": 192,
        },
        {
          month: "months.june",
          MJ: 168,
          "Spider Man": 132,
        },
        {
          month: "months.july",
          MJ: 235,
          "Spider Man": 204,
        },
        {
          month: "months.august",
          MJ: 539,
          "Spider Man": 447,
        },
        {
          month: "months.september",
          MJ: 422,
          "Spider Man": 373,
        },
        {
          month: "months.october",
          MJ: 285,
          "Spider Man": 261,
        },
        {
          month: "months.november",
          MJ: 444,
          "Spider Man": 416,
        },
        {
          month: "months.december",
          MJ: 226,
          "Spider Man": 220,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    timeOfDay: {
      hourCounts: [
        {
          hour: 0,
          label: "00:00",
          MJ: 94,
          "Spider Man": 84,
        },
        {
          hour: 1,
          label: "01:00",
          MJ: 21,
          "Spider Man": 24,
        },
        {
          hour: 2,
          label: "02:00",
          MJ: 23,
          "Spider Man": 7,
        },
        {
          hour: 3,
          label: "03:00",
          MJ: 5,
          "Spider Man": 0,
        },
        {
          hour: 4,
          label: "04:00",
          MJ: 4,
          "Spider Man": 2,
        },
        {
          hour: 5,
          label: "05:00",
          MJ: 3,
          "Spider Man": 2,
        },
        {
          hour: 6,
          label: "06:00",
          MJ: 28,
          "Spider Man": 10,
        },
        {
          hour: 7,
          label: "07:00",
          MJ: 25,
          "Spider Man": 9,
        },
        {
          hour: 8,
          label: "08:00",
          MJ: 27,
          "Spider Man": 14,
        },
        {
          hour: 9,
          label: "09:00",
          MJ: 80,
          "Spider Man": 83,
        },
        {
          hour: 10,
          label: "10:00",
          MJ: 153,
          "Spider Man": 155,
        },
        {
          hour: 11,
          label: "11:00",
          MJ: 202,
          "Spider Man": 158,
        },
        {
          hour: 12,
          label: "12:00",
          MJ: 288,
          "Spider Man": 221,
        },
        {
          hour: 13,
          label: "13:00",
          MJ: 153,
          "Spider Man": 142,
        },
        {
          hour: 14,
          label: "14:00",
          MJ: 411,
          "Spider Man": 356,
        },
        {
          hour: 15,
          label: "15:00",
          MJ: 229,
          "Spider Man": 215,
        },
        {
          hour: 16,
          label: "16:00",
          MJ: 260,
          "Spider Man": 203,
        },
        {
          hour: 17,
          label: "17:00",
          MJ: 357,
          "Spider Man": 275,
        },
        {
          hour: 18,
          label: "18:00",
          MJ: 286,
          "Spider Man": 272,
        },
        {
          hour: 19,
          label: "19:00",
          MJ: 233,
          "Spider Man": 190,
        },
        {
          hour: 20,
          label: "20:00",
          MJ: 168,
          "Spider Man": 177,
        },
        {
          hour: 21,
          label: "21:00",
          MJ: 261,
          "Spider Man": 246,
        },
        {
          hour: 22,
          label: "22:00",
          MJ: 370,
          "Spider Man": 322,
        },
        {
          hour: 23,
          label: "23:00",
          MJ: 184,
          "Spider Man": 160,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    firstMessages: {
      monthlyInitiations: [
        {
          month: "months.january",
          MJ: 13,
          "Spider Man": 7,
        },
        {
          month: "months.february",
          MJ: 9,
          "Spider Man": 8,
        },
        {
          month: "months.march",
          MJ: 7,
          "Spider Man": 11,
        },
        {
          month: "months.april",
          MJ: 12,
          "Spider Man": 12,
        },
        {
          month: "months.may",
          MJ: 12,
          "Spider Man": 6,
        },
        {
          month: "months.june",
          MJ: 12,
          "Spider Man": 11,
        },
        {
          month: "months.july",
          MJ: 7,
          "Spider Man": 15,
        },
        {
          month: "months.august",
          MJ: 10,
          "Spider Man": 5,
        },
        {
          month: "months.september",
          MJ: 14,
          "Spider Man": 9,
        },
        {
          month: "months.october",
          MJ: 14,
          "Spider Man": 12,
        },
        {
          month: "months.november",
          MJ: 15,
          "Spider Man": 10,
        },
        {
          month: "months.december",
          MJ: 9,
          "Spider Man": 13,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    reactions: {
      topReactions: [
        {
          emoji: "😁",
          stats: {
            totalCount: 81,
            userCounts: {
              "Spider Man": 69,
              MJ: 12,
            },
          },
        },
        {
          emoji: "❤",
          stats: {
            totalCount: 63,
            userCounts: {
              "Spider Man": 46,
              MJ: 17,
            },
          },
        },
        {
          emoji: "👍",
          stats: {
            totalCount: 55,
            userCounts: {
              MJ: 9,
              "Spider Man": 46,
            },
          },
        },
        {
          emoji: "🤯",
          stats: {
            totalCount: 43,
            userCounts: {
              "Spider Man": 42,
              MJ: 1,
            },
          },
        },
        {
          emoji: "🔥",
          stats: {
            totalCount: 33,
            userCounts: {
              "Spider Man": 23,
              MJ: 10,
            },
          },
        },
      ],
      userFavorites: [
        {
          user: "Spider Man",
          emoji: "😁",
          count: 69,
        },
        {
          user: "MJ",
          emoji: "🥰",
          count: 27,
        },
      ],
    },
    voiceMessages: {
      userStats: [
        {
          user: "MJ",
          count: 78,
          longestMessage: 178,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 22,
          longestMessage: 120,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 78,
        longestMessage: 178,
        userId: "mjid",
      },
      totalCount: 100,
    },
    videoMessages: {
      userStats: [
        {
          user: "MJ",
          count: 96,
          longestMessage: 60,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 54,
          longestMessage: 59,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 96,
        longestMessage: 60,
        userId: "mjid",
      },
      totalCount: 150,
    },
    wordCloud: {
      wordData:[
        { text: "me", value: 185 },
        { text: "need", value: 146 },
        { text: "you", value: 107 },
        { text: "good", value: 107 },
        { text: "you", value: 106 },
        { text: "can", value: 105 },
        { text: "only", value: 87 },
        { text: "also", value: 85 },
        { text: "want", value: 83 },
        { text: "just", value: 82 },
        { text: "if", value: 82 },
        { text: "later", value: 70 },
        { text: "have", value: 69 },
        { text: "bye", value: 68 },
        { text: "minutes", value: 67 },
        { text: "after", value: 66 },
        { text: "will", value: 62 },
        { text: "hi", value: 60 },
        { text: "will", value: 58 },
        { text: "to", value: 55 },
        { text: "today", value: 55 },
        { text: "was", value: 55 },
        { text: "when", value: 54 },
        { text: "let's", value: 50 },
        { text: "fine", value: 49 },
        { text: "actually", value: 45 },
        { text: "could", value: 44 },
        { text: "haha", value: 44 },
        { text: "then", value: 43 },
        { text: "because", value: 42 },
        { text: "home", value: 41 },
        { text: "maybe", value: 41 },
        { text: "thought", value: 41 },
        { text: "back", value: 41 },
        { text: "more", value: 41 },
        { text: "sleep", value: 39 },
        { text: "morning", value: 39 },
        { text: "why", value: 38 },
        { text: "like", value: 38 },
        { text: "tomorrow", value: 37 },
        { text: "know", value: 37 },
        { text: "day", value: 36 },
        { text: "now", value: 36 },
        { text: "such", value: 36 },
        { text: "alright", value: 35 },
        { text: "even", value: 35 },
        { text: "very", value: 34 },
        { text: "nowadays", value: 34 },
        { text: "one", value: 33 },
        { text: "nothing", value: 32 },
        { text: "goodnight", value: 31 },
        { text: "may", value: 30 },
        { text: "damn", value: 30 },
        { text: "go", value: 30 },
        { text: "will", value: 29 },
        { text: "how much", value: 29 },
        { text: "think", value: 29 },
        { text: "a lot", value: 29 },
        { text: "by the way", value: 28 },
        { text: "sorta", value: 28 },
        { text: "night", value: 27 },
        { text: "wanted", value: 26 },
        { text: "want", value: 26 },
        { text: "seems", value: 26 },
        { text: "soon", value: 25 },
        { text: "lol", value: 25 },
        { text: "rofl", value: 24 },
        { text: "probably", value: 24 },
        { text: "hehe", value: 24 },
        { text: "was", value: 23 },
        { text: "other", value: 23 },
        { text: "time", value: 22 },
        { text: "watch", value: 22 },
        { text: "what for", value: 22 },
        { text: "buy", value: 22 },
        { text: "works", value: 22 },
        { text: "yesterday", value: 22 },
        { text: "what", value: 21 },
        { text: "so", value: 20 },
        { text: "shall", value: 20 },
        { text: "work", value: 20 },
        { text: "myself", value: 19 },
        { text: "store", value: 19 },
        { text: "long", value: 19 },
        { text: "any", value: 19 },
        { text: "this", value: 19 },
        { text: "with you", value: 19 },
        { text: "cool", value: 19 },
        { text: "things", value: 19 },
        { text: "like that", value: 19 },
        { text: "decided", value: 19 },
        { text: "awesome", value: 19 },
        { text: "afterwards", value: 19 },
        { text: "again", value: 19 },
        { text: "thanks", value: 18 },
        { text: "where", value: 18 },
        { text: "decent", value: 18 },
        { text: "hope", value: 18 },
        { text: "sitting", value: 18 },
        { text: "which", value: 17 },
      ],
    },
    forwardedMessages: {
      userStats: [
        {
          user: "Spider Man",
          userId: "paukid",
          sources: [
            {
              source: "The New York Times",
              count: 21,
            },
            {
              source: "Science Spiders",
              count: 10,
            },
            {
              source: "memes.fun",
              count: 7,
            },
          ],
        },
        {
          user: "MJ",
          userId: "mjid",
          sources: [
            {
              source: "very funny pictures",
              count: 9,
            },
            {
              source: "The New York Times",
              count: 4,
            },
            {
              source: "Tony Stark",
              count: 4,
            },
          ],
        },
      ],
      totalCount: 125,
    },
    settings: {
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
      years: [2025, 2024, 2023],
    },
  },
  "2025": {
    messages: {
      monthlyData: [
        {
          month: "months.january",
          MJ: 247,
          "Spider Man": 216,
        },
        {
          month: "months.february",
          MJ: 710,
          "Spider Man": 682,
        },
        {
          month: "months.march",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.april",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.may",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.june",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.july",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.august",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.september",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.october",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.november",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.december",
          MJ: 0,
          "Spider Man": 0,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    timeOfDay: {
      hourCounts: [
        {
          hour: 0,
          label: "00:00",
          MJ: 103,
          "Spider Man": 130,
        },
        {
          hour: 1,
          label: "01:00",
          MJ: 0,
          "Spider Man": 1,
        },
        {
          hour: 2,
          label: "02:00",
          MJ: 1,
          "Spider Man": 0,
        },
        {
          hour: 3,
          label: "03:00",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          hour: 4,
          label: "04:00",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          hour: 5,
          label: "05:00",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          hour: 6,
          label: "06:00",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          hour: 7,
          label: "07:00",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          hour: 8,
          label: "08:00",
          MJ: 2,
          "Spider Man": 2,
        },
        {
          hour: 9,
          label: "09:00",
          MJ: 21,
          "Spider Man": 9,
        },
        {
          hour: 10,
          label: "10:00",
          MJ: 30,
          "Spider Man": 23,
        },
        {
          hour: 11,
          label: "11:00",
          MJ: 51,
          "Spider Man": 46,
        },
        {
          hour: 12,
          label: "12:00",
          MJ: 49,
          "Spider Man": 52,
        },
        {
          hour: 13,
          label: "13:00",
          MJ: 41,
          "Spider Man": 31,
        },
        {
          hour: 14,
          label: "14:00",
          MJ: 74,
          "Spider Man": 61,
        },
        {
          hour: 15,
          label: "15:00",
          MJ: 58,
          "Spider Man": 39,
        },
        {
          hour: 16,
          label: "16:00",
          MJ: 60,
          "Spider Man": 48,
        },
        {
          hour: 17,
          label: "17:00",
          MJ: 94,
          "Spider Man": 82,
        },
        {
          hour: 18,
          label: "18:00",
          MJ: 65,
          "Spider Man": 57,
        },
        {
          hour: 19,
          label: "19:00",
          MJ: 72,
          "Spider Man": 56,
        },
        {
          hour: 20,
          label: "20:00",
          MJ: 48,
          "Spider Man": 43,
        },
        {
          hour: 21,
          label: "21:00",
          MJ: 48,
          "Spider Man": 52,
        },
        {
          hour: 22,
          label: "22:00",
          MJ: 68,
          "Spider Man": 81,
        },
        {
          hour: 23,
          label: "23:00",
          MJ: 72,
          "Spider Man": 85,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    firstMessages: {
      monthlyInitiations: [
        {
          month: "months.january",
          MJ: 16,
          "Spider Man": 7,
        },
        {
          month: "months.february",
          MJ: 7,
          "Spider Man": 5,
        },
        {
          month: "months.march",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.april",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.may",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.june",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.july",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.august",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.september",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.october",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.november",
          MJ: 0,
          "Spider Man": 0,
        },
        {
          month: "months.december",
          MJ: 0,
          "Spider Man": 0,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    reactions: {
      topReactions: [
        {
          emoji: "❤",
          stats: {
            totalCount: 25,
            userCounts: {
              MJ: 8,
              "Spider Man": 17,
            },
          },
        },
        {
          emoji: "😁",
          stats: {
            totalCount: 19,
            userCounts: {
              "Spider Man": 18,
              MJ: 1,
            },
          },
        },
        {
          emoji: "😭",
          stats: {
            totalCount: 17,
            userCounts: {
              "Spider Man": 9,
              MJ: 8,
            },
          },
        },
        {
          emoji: "🔥",
          stats: {
            totalCount: 9,
            userCounts: {
              MJ: 5,
              "Spider Man": 4,
            },
          },
        },
        {
          emoji: "💯",
          stats: {
            totalCount: 7,
            userCounts: {
              "Spider Man": 7,
            },
          },
        },
      ],
      userFavorites: [
        {
          user: "Spider Man",
          emoji: "😁",
          count: 18,
        },
        {
          user: "MJ",
          emoji: "😭",
          count: 8,
        },
      ],
    },
    voiceMessages: {
      userStats: [
        {
          user: "MJ",
          count: 11,
          longestMessage: 155,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 2,
          longestMessage: 23,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 11,
        longestMessage: 155,
        userId: "mjid",
      },
      totalCount: 13,
    },
    videoMessages: {
      userStats: [
        {
          user: "MJ",
          count: 63,
          longestMessage: 59,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 19,
          longestMessage: 59,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 63,
        longestMessage: 59,
        userId: "mjid",
      },
      totalCount: 82,
    },
    wordCloud: {
      wordData: [
        { text: "me", value: 185 },
        { text: "need", value: 146 },
        { text: "you", value: 107 },
        { text: "good", value: 107 },
        { text: "you", value: 106 },
        { text: "can", value: 105 },
        { text: "only", value: 87 },
        { text: "also", value: 85 },
        { text: "want", value: 83 },
        { text: "just", value: 82 },
        { text: "if", value: 82 },
        { text: "later", value: 70 },
        { text: "have", value: 69 },
        { text: "bye", value: 68 },
        { text: "minutes", value: 67 },
        { text: "after", value: 66 },
        { text: "will", value: 62 },
        { text: "hi", value: 60 },
        { text: "will", value: 58 },
        { text: "to", value: 55 },
        { text: "today", value: 55 },
        { text: "was", value: 55 },
        { text: "when", value: 54 },
        { text: "let's", value: 50 },
        { text: "fine", value: 49 },
        { text: "actually", value: 45 },
        { text: "could", value: 44 },
        { text: "haha", value: 44 },
        { text: "then", value: 43 },
        { text: "because", value: 42 },
        { text: "home", value: 41 },
        { text: "maybe", value: 41 },
        { text: "thought", value: 41 },
        { text: "back", value: 41 },
        { text: "more", value: 41 },
        { text: "sleep", value: 39 },
        { text: "morning", value: 39 },
        { text: "why", value: 38 },
        { text: "like", value: 38 },
        { text: "tomorrow", value: 37 },
        { text: "know", value: 37 },
        { text: "day", value: 36 },
        { text: "now", value: 36 },
        { text: "such", value: 36 },
        { text: "alright", value: 35 },
        { text: "even", value: 35 },
        { text: "very", value: 34 },
        { text: "nowadays", value: 34 },
        { text: "one", value: 33 },
        { text: "nothing", value: 32 },
        { text: "goodnight", value: 31 },
        { text: "may", value: 30 },
        { text: "damn", value: 30 },
        { text: "go", value: 30 },
        { text: "will", value: 29 },
        { text: "how much", value: 29 },
        { text: "think", value: 29 },
        { text: "a lot", value: 29 },
        { text: "by the way", value: 28 },
        { text: "sorta", value: 28 },
        { text: "night", value: 27 },
        { text: "wanted", value: 26 },
        { text: "want", value: 26 },
        { text: "seems", value: 26 },
        { text: "soon", value: 25 },
        { text: "lol", value: 25 },
        { text: "rofl", value: 24 },
        { text: "probably", value: 24 },
        { text: "hehe", value: 24 },
        { text: "was", value: 23 },
        { text: "other", value: 23 },
        { text: "time", value: 22 },
        { text: "watch", value: 22 },
        { text: "what for", value: 22 },
        { text: "buy", value: 22 },
        { text: "works", value: 22 },
        { text: "yesterday", value: 22 },
        { text: "what", value: 21 },
        { text: "so", value: 20 },
        { text: "shall", value: 20 },
        { text: "work", value: 20 },
        { text: "myself", value: 19 },
        { text: "store", value: 19 },
        { text: "long", value: 19 },
        { text: "any", value: 19 },
        { text: "this", value: 19 },
        { text: "with you", value: 19 },
        { text: "cool", value: 19 },
        { text: "things", value: 19 },
        { text: "like that", value: 19 },
        { text: "decided", value: 19 },
        { text: "awesome", value: 19 },
        { text: "afterwards", value: 19 },
        { text: "again", value: 19 },
        { text: "thanks", value: 18 },
        { text: "where", value: 18 },
        { text: "decent", value: 18 },
        { text: "hope", value: 18 },
        { text: "sitting", value: 18 },
        { text: "which", value: 17 },
      ],
    },
    forwardedMessages: {
      userStats: [
        {
          user: "MJ",
          userId: "mjid",
          sources: [
            {
              source: "The Daily Bugle",
              count: 12,
            },
            {
              source: "Spider Pictures",
              count: 2,
            },
            {
              source: "The New York Times",
              count: 2,
            },
          ],
        },
        {
          user: "Spider Man",
          userId: "paukid",
          sources: [
            {
              source: "Typical New York",
              count: 5,
            },
            {
              source: "The New York Times",
              count: 3,
            },
            {
              source: "The Daily Bugle",
              count: 2,
            },
          ],
        },
      ],
      totalCount: 40,
    },
    settings: {
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
      years: [2025, 2024, 2023],
    },
  },
  all: {
    messages: {
      monthlyData: [
        {
          month: "months.january",
          MJ: 2221,
          "Spider Man": 2251,
        },
        {
          month: "months.february",
          MJ: 1505,
          "Spider Man": 1480,
        },
        {
          month: "months.march",
          MJ: 1899,
          "Spider Man": 2468,
        },
        {
          month: "months.april",
          MJ: 554,
          "Spider Man": 866,
        },
        {
          month: "months.may",
          MJ: 1303,
          "Spider Man": 1302,
        },
        {
          month: "months.june",
          MJ: 1859,
          "Spider Man": 2169,
        },
        {
          month: "months.july",
          MJ: 3231,
          "Spider Man": 3885,
        },
        {
          month: "months.august",
          MJ: 1126,
          "Spider Man": 1337,
        },
        {
          month: "months.september",
          MJ: 1098,
          "Spider Man": 1225,
        },
        {
          month: "months.october",
          MJ: 1245,
          "Spider Man": 1181,
        },
        {
          month: "months.november",
          MJ: 1882,
          "Spider Man": 1970,
        },
        {
          month: "months.december",
          MJ: 1270,
          "Spider Man": 1710,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    timeOfDay: {
      hourCounts: [
        {
          hour: 0,
          label: "00:00",
          MJ: 1086,
          "Spider Man": 1224,
        },
        {
          hour: 1,
          label: "01:00",
          MJ: 342,
          "Spider Man": 426,
        },
        {
          hour: 2,
          label: "02:00",
          MJ: 113,
          "Spider Man": 117,
        },
        {
          hour: 3,
          label: "03:00",
          MJ: 89,
          "Spider Man": 46,
        },
        {
          hour: 4,
          label: "04:00",
          MJ: 12,
          "Spider Man": 9,
        },
        {
          hour: 5,
          label: "05:00",
          MJ: 18,
          "Spider Man": 11,
        },
        {
          hour: 6,
          label: "06:00",
          MJ: 48,
          "Spider Man": 19,
        },
        {
          hour: 7,
          label: "07:00",
          MJ: 115,
          "Spider Man": 51,
        },
        {
          hour: 8,
          label: "08:00",
          MJ: 280,
          "Spider Man": 274,
        },
        {
          hour: 9,
          label: "09:00",
          MJ: 528,
          "Spider Man": 520,
        },
        {
          hour: 10,
          label: "10:00",
          MJ: 905,
          "Spider Man": 1071,
        },
        {
          hour: 11,
          label: "11:00",
          MJ: 939,
          "Spider Man": 938,
        },
        {
          hour: 12,
          label: "12:00",
          MJ: 922,
          "Spider Man": 883,
        },
        {
          hour: 13,
          label: "13:00",
          MJ: 867,
          "Spider Man": 951,
        },
        {
          hour: 14,
          label: "14:00",
          MJ: 1123,
          "Spider Man": 1179,
        },
        {
          hour: 15,
          label: "15:00",
          MJ: 894,
          "Spider Man": 1107,
        },
        {
          hour: 16,
          label: "16:00",
          MJ: 1130,
          "Spider Man": 1339,
        },
        {
          hour: 17,
          label: "17:00",
          MJ: 1360,
          "Spider Man": 1699,
        },
        {
          hour: 18,
          label: "18:00",
          MJ: 1081,
          "Spider Man": 1267,
        },
        {
          hour: 19,
          label: "19:00",
          MJ: 1131,
          "Spider Man": 1119,
        },
        {
          hour: 20,
          label: "20:00",
          MJ: 1019,
          "Spider Man": 1068,
        },
        {
          hour: 21,
          label: "21:00",
          MJ: 1545,
          "Spider Man": 1909,
        },
        {
          hour: 22,
          label: "22:00",
          MJ: 1970,
          "Spider Man": 2543,
        },
        {
          hour: 23,
          label: "23:00",
          MJ: 1676,
          "Spider Man": 2074,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    firstMessages: {
      monthlyInitiations: [
        {
          month: "months.january",
          MJ: 64,
          "Spider Man": 36,
        },
        {
          month: "months.february",
          MJ: 54,
          "Spider Man": 52,
        },
        {
          month: "months.march",
          MJ: 44,
          "Spider Man": 47,
        },
        {
          month: "months.april",
          MJ: 49,
          "Spider Man": 51,
        },
        {
          month: "months.may",
          MJ: 53,
          "Spider Man": 41,
        },
        {
          month: "months.june",
          MJ: 44,
          "Spider Man": 46,
        },
        {
          month: "months.july",
          MJ: 30,
          "Spider Man": 38,
        },
        {
          month: "months.august",
          MJ: 56,
          "Spider Man": 31,
        },
        {
          month: "months.september",
          MJ: 46,
          "Spider Man": 55,
        },
        {
          month: "months.october",
          MJ: 59,
          "Spider Man": 51,
        },
        {
          month: "months.november",
          MJ: 63,
          "Spider Man": 52,
        },
        {
          month: "months.december",
          MJ: 53,
          "Spider Man": 56,
        },
      ],
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
    },
    reactions: {
      topReactions: [
        {
          emoji: "😁",
          stats: {
            totalCount: 166,
            userCounts: {
              MJ: 25,
              "Spider Man": 141,
            },
          },
        },
        {
          emoji: "❤",
          stats: {
            totalCount: 161,
            userCounts: {
              MJ: 58,
              "Spider Man": 103,
            },
          },
        },
        {
          emoji: "👍",
          stats: {
            totalCount: 127,
            userCounts: {
              MJ: 42,
              "Spider Man": 85,
            },
          },
        },
        {
          emoji: "🥰",
          stats: {
            totalCount: 102,
            userCounts: {
              "Spider Man": 43,
              MJ: 59,
            },
          },
        },
        {
          emoji: "🔥",
          stats: {
            totalCount: 81,
            userCounts: {
              MJ: 34,
              "Spider Man": 47,
            },
          },
        },
      ],
      userFavorites: [
        {
          user: "Spider Man",
          emoji: "😁",
          count: 141,
        },
        {
          user: "MJ",
          emoji: "🥰",
          count: 59,
        },
      ],
    },
    voiceMessages: {
      userStats: [
        {
          user: "MJ",
          count: 215,
          longestMessage: 305,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 162,
          longestMessage: 190,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 215,
        longestMessage: 305,
        userId: "mjid",
      },
      totalCount: 377,
    },
    videoMessages: {
      userStats: [
        {
          user: "MJ",
          count: 416,
          longestMessage: 62,
          userId: "mjid",
        },
        {
          user: "Spider Man",
          count: 148,
          longestMessage: 60,
          userId: "paukid",
        },
      ],
      longestMessageStats: {
        user: "MJ",
        count: 416,
        longestMessage: 62,
        userId: "mjid",
      },
      totalCount: 564,
    },
    wordCloud: {
      wordData: [
        { text: "me", value: 185 },
        { text: "need", value: 146 },
        { text: "you", value: 107 },
        { text: "good", value: 107 },
        { text: "you", value: 106 },
        { text: "can", value: 105 },
        { text: "only", value: 87 },
        { text: "also", value: 85 },
        { text: "want", value: 83 },
        { text: "just", value: 82 },
        { text: "if", value: 82 },
        { text: "later", value: 70 },
        { text: "have", value: 69 },
        { text: "bye", value: 68 },
        { text: "minutes", value: 67 },
        { text: "after", value: 66 },
        { text: "will", value: 62 },
        { text: "hi", value: 60 },
        { text: "will", value: 58 },
        { text: "to", value: 55 },
        { text: "today", value: 55 },
        { text: "was", value: 55 },
        { text: "when", value: 54 },
        { text: "let's", value: 50 },
        { text: "fine", value: 49 },
        { text: "actually", value: 45 },
        { text: "could", value: 44 },
        { text: "haha", value: 44 },
        { text: "then", value: 43 },
        { text: "because", value: 42 },
        { text: "home", value: 41 },
        { text: "maybe", value: 41 },
        { text: "thought", value: 41 },
        { text: "back", value: 41 },
        { text: "more", value: 41 },
        { text: "sleep", value: 39 },
        { text: "morning", value: 39 },
        { text: "why", value: 38 },
        { text: "like", value: 38 },
        { text: "tomorrow", value: 37 },
        { text: "know", value: 37 },
        { text: "day", value: 36 },
        { text: "now", value: 36 },
        { text: "such", value: 36 },
        { text: "alright", value: 35 },
        { text: "even", value: 35 },
        { text: "very", value: 34 },
        { text: "nowadays", value: 34 },
        { text: "one", value: 33 },
        { text: "nothing", value: 32 },
        { text: "goodnight", value: 31 },
        { text: "may", value: 30 },
        { text: "damn", value: 30 },
        { text: "go", value: 30 },
        { text: "will", value: 29 },
        { text: "how much", value: 29 },
        { text: "think", value: 29 },
        { text: "a lot", value: 29 },
        { text: "by the way", value: 28 },
        { text: "sorta", value: 28 },
        { text: "night", value: 27 },
        { text: "wanted", value: 26 },
        { text: "want", value: 26 },
        { text: "seems", value: 26 },
        { text: "soon", value: 25 },
        { text: "lol", value: 25 },
        { text: "rofl", value: 24 },
        { text: "probably", value: 24 },
        { text: "hehe", value: 24 },
        { text: "was", value: 23 },
        { text: "other", value: 23 },
        { text: "time", value: 22 },
        { text: "watch", value: 22 },
        { text: "what for", value: 22 },
        { text: "buy", value: 22 },
        { text: "works", value: 22 },
        { text: "yesterday", value: 22 },
        { text: "what", value: 21 },
        { text: "so", value: 20 },
        { text: "shall", value: 20 },
        { text: "work", value: 20 },
        { text: "myself", value: 19 },
        { text: "store", value: 19 },
        { text: "long", value: 19 },
        { text: "any", value: 19 },
        { text: "this", value: 19 },
        { text: "with you", value: 19 },
        { text: "cool", value: 19 },
        { text: "things", value: 19 },
        { text: "like that", value: 19 },
        { text: "decided", value: 19 },
        { text: "awesome", value: 19 },
        { text: "afterwards", value: 19 },
        { text: "again", value: 19 },
        { text: "thanks", value: 18 },
        { text: "where", value: 18 },
        { text: "decent", value: 18 },
        { text: "hope", value: 18 },
        { text: "sitting", value: 18 },
        { text: "which", value: 17 },
      ],
    },
    forwardedMessages: {
      userStats: [
        {
          user: "Spider Man",
          userId: "paukid",
          sources: [
            {
              source: "Rent Apartment | New York",
              count: 226,
            },
            {
              source: "The New York Times",
              count: 104,
            },
            {
              source: "cafes in New Yourk",
              count: 84,
            },
          ],
        },
        {
          user: "MJ",
          userId: "mjid",
          sources: [
            {
              source: "The New York Times",
              count: 64,
            },
            {
              source: "Tony Stark",
              count: 28,
            },
            {
              source: "Stan Lee",
              count: 25,
            },
          ],
        },
      ],
      totalCount: 1176,
    },
    settings: {
      users: ["MJ", "Spider Man"],
      userIdMap: {
        MJ: "mjid",
        "Spider Man": "paukid",
      },
      years: [2025, 2024, 2023],
    },
  },
};
